/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package MusicPlayerMain;
import java.io.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author Monika
 */
public class NewFrame extends java.awt.Frame {
    Long CurrentFrame;
    Clip clip;
    static int clipsize;  
    Thread thread;
    int id_Num = 0;
    String Filepath, FileName, FileImage;
    
     public void change(){ // Changing of songs
            Playlist playlist = new Playlist();
            Filepath = playlist.FileAdd(id_Num);
            FileName = playlist.GetName(id_Num);
            FileImage = playlist.GetImage(id_Num);
    }
    public void play(){ //Song playing commands
        try{
            AudioInputStream snd = AudioSystem.getAudioInputStream(new File(Filepath).getAbsoluteFile());
            clip = AudioSystem.getClip();
            clip.open(snd);
            clipsize = (int) (clip.getMicrosecondLength()/1000000);
        }
        catch(Exception e){};
    }
    
    public void resetAudio(){ // resetting the audio for pause button
        try{
            AudioInputStream snd = AudioSystem.getAudioInputStream(new File(Filepath).getAbsoluteFile());
            clip.open(snd); 
        }
        catch(Exception e){};
    }

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
        Pause.setVisible(false);
        RESUME.setVisible(false);
        // Progress bar thread
        thread = new Thread(() -> {
            try{
            while(true){
                Progress.setValue((int)(clip.getMicrosecondPosition()/1000000));
                if(Progress.getValue() == clipsize-1){ // progress bar next command
                    clip.stop();
                    Progress.setValue(0);
                    id_Num++;
                    if(id_Num == 4)
                        id_Num = 0;
                    change();
                    play();
                    jLabel1.setIcon(new ImageIcon(FileImage));
                    SongName.setText(FileName);
                    Progress.setMaximum(clipsize);
                    clip.start();
                    }
                }
            }catch(Exception e){};
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SongName = new java.awt.Label();
        Play = new java.awt.Button();
        Pause = new java.awt.Button();
        seekminus = new java.awt.Button();
        RESUME = new java.awt.Button();
        seekplus = new java.awt.Button();
        Progress = new javax.swing.JProgressBar();
        prevSong = new javax.swing.JButton();
        nextSong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 30, 90));
        setForeground(new java.awt.Color(51, 0, 102));
        setMinimumSize(new java.awt.Dimension(512, 413));
        setResizable(false);
        setTitle("jMusicPlayer");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SongName.setAlignment(java.awt.Label.CENTER);
        SongName.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        SongName.setForeground(new java.awt.Color(255, 255, 255));
        SongName.setText("Now Playing");
        add(SongName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 510, 40));

        Play.setBackground(new java.awt.Color(51, 0, 102));
        Play.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Play.setForeground(new java.awt.Color(255, 255, 255));
        Play.setLabel("Play");
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 60, 30));

        Pause.setBackground(new java.awt.Color(51, 0, 102));
        Pause.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Pause.setForeground(new java.awt.Color(255, 255, 255));
        Pause.setLabel("Pause");
        Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PauseMouseClicked(evt);
            }
        });
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 60, 30));

        seekminus.setActionCommand("NEXT");
        seekminus.setBackground(new java.awt.Color(102, 0, 102));
        seekminus.setForeground(new java.awt.Color(255, 255, 255));
        seekminus.setLabel("-5 Sec");
        seekminus.setName("NEXT\n"); // NOI18N
        seekminus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seekminusMouseClicked(evt);
            }
        });
        add(seekminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 60, 30));

        RESUME.setActionCommand("NEXT");
        RESUME.setBackground(new java.awt.Color(51, 0, 102));
        RESUME.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        RESUME.setForeground(new java.awt.Color(255, 255, 255));
        RESUME.setLabel("Resume");
        RESUME.setName("NEXT\n"); // NOI18N
        RESUME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RESUMEMouseClicked(evt);
            }
        });
        add(RESUME, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 60, 30));

        seekplus.setActionCommand("NEXT");
        seekplus.setBackground(new java.awt.Color(102, 0, 102));
        seekplus.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        seekplus.setForeground(new java.awt.Color(255, 255, 255));
        seekplus.setLabel("+5 Sec");
        seekplus.setName("NEXT\n"); // NOI18N
        seekplus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seekplusMouseClicked(evt);
            }
        });
        seekplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seekplusActionPerformed(evt);
            }
        });
        add(seekplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 60, 30));

        Progress.setForeground(new java.awt.Color(0, 255, 0));
        Progress.setBorder(null);
        Progress.setRequestFocusEnabled(false);
        Progress.setString("");
        Progress.setVerifyInputWhenFocusTarget(false);
        add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 341, 190, 4));

        prevSong.setBackground(new java.awt.Color(102, 0, 102));
        prevSong.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        prevSong.setForeground(new java.awt.Color(255, 255, 255));
        prevSong.setText("Prev");
        prevSong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        prevSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevSongActionPerformed(evt);
            }
        });
        add(prevSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 60, 30));

        nextSong.setBackground(new java.awt.Color(102, 0, 102));
        nextSong.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        nextSong.setForeground(new java.awt.Color(255, 255, 255));
        nextSong.setText("Next");
        nextSong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextSong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextSongActionPerformed(evt);
            }
        });
        add(nextSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 30));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        Pause.setVisible(true);
        Play.setVisible(false);
        change();
        play();
        SongName.setText(FileName);
        jLabel1.setIcon(new ImageIcon(FileImage));
        Progress.setMaximum(clipsize);
        clip.start();
        thread.start();
    }//GEN-LAST:event_PlayMouseClicked

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed

    }//GEN-LAST:event_PlayActionPerformed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PauseActionPerformed

    private void PauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseClicked
        RESUME.setVisible(true);
        Pause.setVisible(false);
        this.CurrentFrame = this.clip.getMicrosecondPosition();
        clip.stop();
    }//GEN-LAST:event_PauseMouseClicked

    private void RESUMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESUMEMouseClicked
        RESUME.setVisible(false);
        Pause.setVisible(true);
        clip.close();
        resetAudio();
        clip.setMicrosecondPosition(CurrentFrame);
        clip.start();
    }//GEN-LAST:event_RESUMEMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void seekplusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seekplusMouseClicked
        clip.stop();
        resetAudio();
        clip.setMicrosecondPosition(clip.getMicrosecondPosition()+5000000);
        if(Pause.isVisible())
            clip.start();
        else;
    }//GEN-LAST:event_seekplusMouseClicked

    private void seekminusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seekminusMouseClicked
        clip.stop();
        resetAudio();
        clip.setMicrosecondPosition(clip.getMicrosecondPosition()-5000000);
        if(RESUME.isVisible());
        else
            clip.start();
    }//GEN-LAST:event_seekminusMouseClicked

    private void prevSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevSongActionPerformed
        id_Num--;
        if(id_Num < 0){
            JOptionPane.showMessageDialog(null, "There is no Previous Song.");
            id_Num = 0;
        }
        else{
        clip.stop();
        Progress.setValue(0);
        change();
        play();
        jLabel1.setIcon(new ImageIcon(FileImage));
        SongName.setText(FileName);
        Progress.setMaximum(clipsize);
        clip.start();}
    }//GEN-LAST:event_prevSongActionPerformed

    private void nextSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextSongActionPerformed
        clip.stop();
        Progress.setValue(0);
        id_Num++;
        if(id_Num == 4)
            id_Num = 0;
        change();
        play();
        jLabel1.setIcon(new ImageIcon(FileImage));
        SongName.setText(FileName);
        Progress.setMaximum(clipsize);
        clip.start();
    }//GEN-LAST:event_nextSongActionPerformed

    private void seekplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seekplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seekplusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Pause;
    private java.awt.Button Play;
    public javax.swing.JProgressBar Progress;
    private java.awt.Button RESUME;
    private java.awt.Label SongName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextSong;
    private javax.swing.JButton prevSong;
    private java.awt.Button seekminus;
    private java.awt.Button seekplus;
    // End of variables declaration//GEN-END:variables
}
